# Generated by Django 6.0 on 2026-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
