# Generated by Django 6.0 on 2026-04-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_short_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='randomize_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='randomize_pages',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuestionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('contains_option', 'Contains option'), ('gt', 'Greater than'), ('lt', 'Less than'), ('is_answered', 'Is answered')], max_length=32)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.question')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_conditions', to='surveys.question')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='surveys.survey')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_page', to='surveys.surveypage'),
        ),
    ]
