# Generated by Django 6.0 on 2026-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_question_randomize_options_survey_randomize_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('single', 'Single'), ('multi', 'Multi'), ('text', 'Text'), ('scale', 'Scale'), ('dropdown', 'Dropdown'), ('yesno', 'Yes/No'), ('number', 'Number'), ('date', 'Date')], default='single', max_length=10),
        ),
    ]
