# Generated by Django 6.0 on 2026-04-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_question_qtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('single', 'Single'), ('multi', 'Multi'), ('text', 'Text'), ('scale', 'Scale'), ('dropdown', 'Dropdown'), ('yesno', 'Yes/No'), ('number', 'Number'), ('date', 'Date'), ('matrix_single', 'Matrix Single'), ('matrix_multi', 'Matrix Multi')], default='single', max_length=15),
        ),
        migrations.CreateModel(
            name='MatrixColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, default='', max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_columns', to='surveys.question')),
            ],
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, default='', max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rows', to='surveys.question')),
            ],
        ),
        migrations.CreateModel(
            name='MatrixAnswerCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_cells', to='surveys.answer')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.matrixcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.matrixrow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('answer', 'row', 'column'), name='unique_matrix_cell')],
            },
        ),
    ]
