# Generated by Django 6.0 on 2026-04-16 15:18

from django.db import migrations, models


def merge_duplicate_answers(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")
    MatrixAnswerCell = apps.get_model("surveys", "MatrixAnswerCell")

    duplicates = (
        Answer.objects
        .values("response_id", "question_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )

    for group in duplicates:
        answers = list(
            Answer.objects
            .filter(response_id=group["response_id"], question_id=group["question_id"])
            .order_by("id")
        )
        keeper = answers[0]

        for duplicate in answers[1:]:
            changed_fields = []
            if not keeper.text and duplicate.text:
                keeper.text = duplicate.text
                changed_fields.append("text")
            if keeper.num is None and duplicate.num is not None:
                keeper.num = duplicate.num
                changed_fields.append("num")
            if changed_fields:
                keeper.save(update_fields=changed_fields)

            for option in duplicate.selected_options.all():
                keeper.selected_options.add(option)

            for cell in MatrixAnswerCell.objects.filter(answer=duplicate):
                cell_exists = MatrixAnswerCell.objects.filter(
                    answer=keeper,
                    row_id=cell.row_id,
                    column_id=cell.column_id,
                ).exists()
                if cell_exists:
                    cell.delete()
                else:
                    cell.answer = keeper
                    cell.save(update_fields=["answer"])

            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_question_qtype_matrixcolumn_matrixrow_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_answers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_response_question'),
        ),
    ]
