# Generated by Django 6.0 on 2026-04-17 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_answer_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('single', 'Single'), ('multi', 'Multi'), ('text', 'Text'), ('scale', 'Scale'), ('dropdown', 'Dropdown'), ('yesno', 'Yes/No'), ('number', 'Number'), ('date', 'Date'), ('matrix_single', 'Matrix Single'), ('matrix_multi', 'Matrix Multi'), ('ranking', 'Ranking')], default='single', max_length=15),
        ),
        migrations.CreateModel(
            name='RankingAnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_items', to='surveys.answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.option')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('answer', 'option'), name='unique_ranking_option_per_answer'), models.UniqueConstraint(fields=('answer', 'rank'), name='unique_ranking_rank_per_answer')],
            },
        ),
    ]
