# Generated by Django 6.0 on 2026-04-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_question_qtype_rankingansweritem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncondition',
            options={'ordering': ['priority', 'id']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='action',
            field=models.CharField(choices=[('show_question', 'Show question'), ('show_page', 'Show page'), ('jump_to_page', 'Jump to page'), ('terminate', 'Terminate survey')], default='show_question', max_length=32),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='group_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='group_logic',
            field=models.CharField(choices=[('all', 'All conditions in group must match'), ('any', 'Any condition in group may match')], default='all', max_length=8),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.surveypage'),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='target_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_conditions', to='surveys.surveypage'),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='terminate_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='response',
            name='complete_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed normally'), ('screened_out', 'Screened out')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='response',
            name='screened_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='screened_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='screened_out_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questioncondition',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('contains_option', 'Contains option'), ('gt', 'Greater than'), ('lt', 'Less than'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('is_answered', 'Is answered'), ('not_answered', 'Not answered')], max_length=32),
        ),
        migrations.AlterField(
            model_name='questioncondition',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='questioncondition',
            name='source_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_conditions', to='surveys.question'),
        ),
    ]
