# Generated by Django 6.0 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_analysisreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticresults',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='analyticresults',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analyticresults',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='analyticresults',
            name='atype',
        ),
    ]
