# Generated by Django 6.0 on 2026-05-28 07:44

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_condition_groups(apps, schema_editor):
    QuestionCondition = apps.get_model('surveys', 'QuestionCondition')
    QuestionConditionGroup = apps.get_model('surveys', 'QuestionConditionGroup')

    groups_by_key = {}
    for condition in QuestionCondition.objects.select_related('source_question').exclude(group_key=''):
        survey_id = condition.source_question.survey_id
        title = condition.group_key
        key = (survey_id, title)
        group = groups_by_key.get(key)
        if group is None:
            group, _ = QuestionConditionGroup.objects.get_or_create(
                survey_id=survey_id,
                title=title,
                defaults={
                    'logic': condition.group_logic or 'all',
                    'priority': condition.priority,
                    'is_active': condition.is_active,
                },
            )
            groups_by_key[key] = group

        condition.group_id = group.id
        condition.save(update_fields=['group'])


def backwards_copy_condition_groups(apps, schema_editor):
    QuestionCondition = apps.get_model('surveys', 'QuestionCondition')
    for condition in QuestionCondition.objects.select_related('group').filter(group__isnull=False):
        condition.group_key = condition.group.title
        condition.group_logic = condition.group.logic
        condition.save(update_fields=['group_key', 'group_logic'])


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_alter_analyticresults_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionConditionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('logic', models.CharField(choices=[('all', 'All conditions in group must match'), ('any', 'Any condition in group may match')], default='all', max_length=8)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups', to='surveys.survey')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='matrix_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.matrixcolumn'),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='matrix_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.matrixrow'),
        ),
        migrations.AlterField(
            model_name='questioncondition',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('contains_option', 'Contains option'), ('gt', 'Greater than'), ('lt', 'Less than'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('is_answered', 'Is answered'), ('not_answered', 'Not answered'), ('contains_matrix_cell', 'Contains matrix cell'), ('matrix_row_equals', 'Matrix row equals'), ('matrix_row_not_equals', 'Matrix row not equals')], max_length=32),
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.questionconditiongroup'),
        ),
        migrations.RunPython(forwards_copy_condition_groups, backwards_copy_condition_groups),
        migrations.RemoveField(
            model_name='questioncondition',
            name='group_key',
        ),
        migrations.RemoveField(
            model_name='questioncondition',
            name='group_logic',
        ),
        migrations.AddIndex(
            model_name='questionconditiongroup',
            index=models.Index(fields=['survey', 'priority'], name='surveys_que_survey__538b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionconditiongroup',
            index=models.Index(fields=['survey', 'is_active'], name='surveys_que_survey__2d17da_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionconditiongroup',
            constraint=models.UniqueConstraint(fields=('survey', 'title'), name='unique_condition_group_title_per_survey'),
        ),
    ]
