# Generated by Django 6.0 on 2026-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_remove_questioncondition_group_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='draft', max_length=10),
        ),
    ]
